wandb_version: 1

epochs:
  desc: null
  value: 65
batch_size_test:
  desc: null
  value: 85
batch_size_val:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.003
momentum:
  desc: null
  value: 0.86
decay:
  desc: null
  value: 0.0005
dataset:
  desc: null
  value: CIFAR-10
architecture:
  desc: null
  value: CNN
optimizer:
  desc: null
  value: SGD+SAM
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701709863.742127
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.4
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
